### ISSUE TITLE
Change in ParserTask.php needed

### ISSUE THREAD

**Issue by andi2802** [pringuin/pimcore-lucene-search#4]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
![Screenshot 2023-05-05 113348](https://user-images.githubusercontent.com/60915613/236424530-048053fb-1778-4ba5-8cc7-fd2334950d9a.png)

| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

**Comment by Cruiser13** [comment]
@andi2802 thank you for your report, could you elaborate the issue a little bit more?

**Comment by andi2802** [comment]
@Cruiser13 sorry, somehow my comment was gone after pasting the screenshot.
There is an index error when you start the crawler.
If you go to the file pimcore-lucene-search/src/LuceneSearchBundle/Task/Parser/ParserTask.php and change the line 'unset($this->index);' to '$this->index = 0' then the error message is gone, crawler runs through and indexes everything.
