### ISSUE TITLE
Autocomplete broken because of routing config error

### ISSUE THREAD

**Issue by LosHawlos** [pringuin/pimcore-lucene-search#7]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Currently the autocomplete feature does not work. Calling the AJAX Url  /lucence-search/auto-complete throws the error:
The controller for URI "/lucence-search/auto-complete" is not callable: Controller "LuceneSearchBundle\Controller\AutoCompleteController:searchAction" does neither exist as service nor as class.

It is caused by a typo in the routing configuration. Looks like Symfony now reqires a double :: as separator for the method name.

PR available: #6

**Comment by Cruiser13** [comment]
Closed in #6
