### ISSUE TITLE
Crawler aborts with exception on some pages

### ISSUE THREAD

**Issue by LosHawlos** [pringuin/pimcore-lucene-search#9]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no

The crawler aborts with the following exception:

In Html.php line 99:

  [ValueError]
  DOMDocument::loadHTML(): Argument # 1 ($source) must not be empty  

Exception trace:
  at /var/www/html/vendor/zf1/zend-search-lucene/library/Zend/Search/Lucene/Document/Html.php:99
 DOMDocument->loadHTML() at /var/www/html/vendor/zf1/zend-search-lucene/library/Zend/Search/Lucene/Document/Html.php:99
 Zend_Search_Lucene_Document_Html->__construct() at /var/www/html/vendor/zf1/zend-search-lucene/library/Zend/Search/Lucene/Document/Html.php:260
 Zend_Search_Lucene_Document_Html::loadHTML() at /var/www/html/vendor/pringuin/pimcore-lucene-search/src/LuceneSearchBundle/Task/Parser/ParserTask.php:760
 LuceneSearchBundle\Task\Parser\ParserTask->parseResponse() at /var/www/html/vendor/pringuin/pimcore-lucene-search/src/LuceneSearchBundle/Task/Parser/ParserTask.php:128

It seems to be related to a page that contains content parts that are to be excluded using the crawler:content_exclude_start_indicator / crawler:content_exclude_end_indicator.

A PR that omits the exception is in PR #8

**Comment by Cruiser13** [comment]
Fixed in #8
